spring:
  application:
    name: onlineLibraryService
---
spring:
  profiles: default
  data:
    rest:
      base-path: /onlineLibraryService
    mongodb:
      host: localhost
      port: 27017
      database: onlineLibrary
      repositories:
        enabled: true
management:
  security:
    enabled: false
